"""Add name field to users table

Revision ID: 156eb2cec3b2
Revises: dc296d05e9d1
Create Date: 2025-08-23 23:10:47.341571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156eb2cec3b2'
down_revision: Union[str, Sequence[str], None] = 'dc296d05e9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add name column as nullable first
    op.add_column('users', sa.Column('name', sa.String(length=150), nullable=True))
    
    # Update existing users with empty name as default
    op.execute("UPDATE users SET name = '' WHERE name IS NULL")
    
    # Now make the column non-nullable
    op.alter_column('users', 'name', nullable=False)
    
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
