"""Add encryption_iv field to documents

Revision ID: c822278260cd
Revises: 63a52c18ad50
Create Date: 2025-08-21 22:24:53.723719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c822278260cd'
down_revision: Union[str, Sequence[str], None] = '63a52c18ad50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('documents', sa.Column('encryption_iv', sa.String(length=100), nullable=True))
    
    # Update existing records with a placeholder IV (they would need re-encryption in real scenario)
    op.execute("UPDATE documents SET encryption_iv = 'placeholder-iv-requires-migration' WHERE encryption_iv IS NULL")
    
    # Now make the column non-nullable
    op.alter_column('documents', 'encryption_iv', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'encryption_iv')
    # ### end Alembic commands ###
