# Railway Deployment Configuration for Briefcase Backend
# This configuration deploys the FastAPI backend with PostgreSQL database

[build]
builder = "nixpacks"
watchPatterns = ["apps/backend/**", "railway.toml"]

[build.nixpacksPlan.variables]
NIXPACKS_PYTHON_PACKAGE_MANAGER = "uv"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python312", "uv"]

[build.nixpacksPlan.phases.install] 
cmds = ["uv sync --no-dev --frozen"]

[deploy]
startCommand = "uv run python main.py"
restartPolicyType = "Never"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 30